title: LOGS.PS1
description: LOGS.PS1 & LOGS.BAT allows you to quickly collect information from a Windows 10 client machine through PowerShell
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
